// Un unico diccionario. Sin libreria de i18n: son dos idiomas y textos planos.
export const dict = {
  es: {
    appName: "apliknte",
    tagline: "Tus candidaturas, ordenadas",
    email: "Correo",
    password: "Contrasena",
    signIn: "Entrar",
    signUp: "Crear cuenta",
    signOut: "Salir",
    noAccount: "No tienes cuenta?",
    haveAccount: "Ya tienes cuenta?",
    checkEmail: "Revisa tu correo para confirmar la cuenta.",
    newApplication: "Nueva candidatura",
    company: "Empresa",
    role: "Puesto",
    source: "Via",
    url: "Enlace a la oferta",
    workMode: "Modalidad",
    salary: "Salario (min - max)",
    appliedOn: "Fecha",
    status: "Estado",
    cv: "CV enviado",
    followUpOn: "Seguimiento",
    save: "Guardar",
    cancel: "Cancelar",
    empty: "Todavia no has registrado ninguna candidatura.",
    emptyCta: "Registra la primera",
    daysAgo: (n: number) => (n === 0 ? "hoy" : n === 1 ? "hace 1 dia" : `hace ${n} dias`),
    total: "candidaturas",
    optional: "opcional",
    presencial: "Presencial",
    hibrido: "Hibrido",
    remoto: "Remoto",
    aplicado: "Aplicado",
    cribado: "Llamada",
    entrevista_1: "Entrevista 1",
    entrevista_2: "Entrevista 2",
    entrevista_3: "Entrevista 3",
    oferta: "Oferta",
    rechazado: "Rechazado",
    retirado: "Retirado",
  },
  en: {
    appName: "apliknte",
    tagline: "Your job applications, sorted",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    signUp: "Sign up",
    signOut: "Sign out",
    noAccount: "No account yet?",
    haveAccount: "Already have an account?",
    checkEmail: "Check your email to confirm your account.",
    newApplication: "New application",
    company: "Company",
    role: "Role",
    source: "Source",
    url: "Job posting link",
    workMode: "Work mode",
    salary: "Salary (min - max)",
    appliedOn: "Date",
    status: "Status",
    cv: "CV sent",
    followUpOn: "Follow-up",
    save: "Save",
    cancel: "Cancel",
    empty: "You haven't logged any application yet.",
    emptyCta: "Log the first one",
    daysAgo: (n: number) => (n === 0 ? "today" : n === 1 ? "1 day ago" : `${n} days ago`),
    total: "applications",
    optional: "optional",
    presencial: "On-site",
    hibrido: "Hybrid",
    remoto: "Remote",
    aplicado: "Applied",
    cribado: "Screening call",
    entrevista_1: "Interview 1",
    entrevista_2: "Interview 2",
    entrevista_3: "Interview 3",
    oferta: "Offer",
    rechazado: "Rejected",
    retirado: "Withdrawn",
  },
};

export type Locale = keyof typeof dict;
export type Dict = (typeof dict)["es"];

export const STATUSES = [
  "aplicado",
  "cribado",
  "entrevista_1",
  "entrevista_2",
  "entrevista_3",
  "oferta",
  "rechazado",
  "retirado",
] as const;

export const WORK_MODES = ["presencial", "hibrido", "remoto"] as const;

export const SOURCES = ["LinkedIn", "InfoJobs", "Indeed", "Web empresa", "Contacto", "Otra"];
