// Un unico diccionario. Sin libreria de i18n: son dos idiomas y textos planos.
export const dict = {
  es: {
    appName: "Apliknte",
    tagline: "Tus candidaturas, ordenadas",
    email: "Correo",
    password: "Contraseña",
    signIn: "Entrar",
    signUp: "Crear cuenta",
    signOut: "Salir",
    noAccount: "¿No tienes cuenta?",
    haveAccount: "¿Ya tienes cuenta?",
    checkEmail: "Revisa tu correo para confirmar la cuenta.",
    passwordHint: "Mínimo 8 caracteres, con mayúscula, minúscula, número y símbolo.",
    newApplication: "Nueva candidatura",
    yourApplications: "Tus candidaturas",
    company: "Empresa",
    role: "Puesto",
    source: "Vía",
    sourceHint: "Dónde viste la oferta o por dónde aplicaste.",
    url: "Enlace a la oferta",
    workMode: "Modalidad",
    workModeHint: "La que ofrece la empresa en la oferta.",
    salary: "Salario anual (miles de €)",
    min: "mínimo",
    max: "máximo",
    notSpecified: "No especifica",
    appliedOn: "Fecha",
    status: "Estado",
    statusHint: "En qué punto está esta candidatura ahora mismo.",
    cv: "CV enviado",
    followUpOn: "Seguimiento",
    followUpHint: "Te lo proponemos a 15 días. Cámbialo si quieres.",
    save: "Guardar",
    cancel: "Cancelar",
    empty: "Todavía no has registrado ninguna candidatura.",
    emptyCta: "Registra la primera",
    daysAgo: (n: number) => (n === 0 ? "hoy" : n === 1 ? "hace 1 día" : `hace ${n} días`),
    total: "candidaturas",
    totalOne: "candidatura",
    contacted: "Contactado",
    notContacted: "¿Ya contactaste?",
    yes: "Sí",
    notYet: "Aún no",
    followUpToday: "Toca contactar hoy",
    followUpDue: (n: number) => (n === 1 ? "Deberías haber contactado hace 1 día" : `Deberías haber contactado hace ${n} días`),
    followUpSoon: (n: number) => (n === 1 ? "Contactar mañana" : `Contactar en ${n} días`),
    optional: "opcional",
    presencial: "Presencial",
    hibrido: "Híbrido",
    remoto: "Remoto",
    no_especifica: "No especifica",
    aplicado: "Sin respuesta",
    cribado: "Me contactaron",
    entrevista_1: "1ª entrevista",
    entrevista_2: "2ª entrevista",
    entrevista_3: "3ª entrevista",
    oferta: "Oferta recibida",
    contratado: "¡Contratado!",
    rechazado: "Rechazado",
    retirado: "Me retiré",
  },
  en: {
    appName: "Apliknte",
    tagline: "Your job applications, sorted",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    signUp: "Sign up",
    signOut: "Sign out",
    noAccount: "No account yet?",
    haveAccount: "Already have an account?",
    checkEmail: "Check your email to confirm your account.",
    passwordHint: "At least 8 characters, with upper, lower, number and symbol.",
    newApplication: "New application",
    yourApplications: "Your applications",
    company: "Company",
    role: "Role",
    source: "Source",
    sourceHint: "Where you saw it or how you applied.",
    url: "Job posting link",
    workMode: "Work mode",
    workModeHint: "What the company offers in the posting.",
    salary: "Annual salary (thousands €)",
    min: "min",
    max: "max",
    notSpecified: "Not specified",
    appliedOn: "Date",
    status: "Status",
    statusHint: "Where this application stands right now.",
    cv: "CV sent",
    followUpOn: "Follow-up",
    followUpHint: "Suggested 15 days ahead. Change it if you want.",
    save: "Save",
    cancel: "Cancel",
    empty: "You haven't logged any application yet.",
    emptyCta: "Log the first one",
    daysAgo: (n: number) => (n === 0 ? "today" : n === 1 ? "1 day ago" : `${n} days ago`),
    total: "applications",
    totalOne: "application",
    contacted: "Followed up",
    notContacted: "Followed up yet?",
    yes: "Yes",
    notYet: "Not yet",
    followUpToday: "Time to follow up today",
    followUpDue: (n: number) => (n === 1 ? "You should have followed up 1 day ago" : `You should have followed up ${n} days ago`),
    followUpSoon: (n: number) => (n === 1 ? "Follow up tomorrow" : `Follow up in ${n} days`),
    optional: "optional",
    presencial: "On-site",
    hibrido: "Hybrid",
    remoto: "Remote",
    no_especifica: "Not specified",
    aplicado: "No reply yet",
    cribado: "They reached out",
    entrevista_1: "1st interview",
    entrevista_2: "2nd interview",
    entrevista_3: "3rd interview",
    oferta: "Offer received",
    contratado: "Hired!",
    rechazado: "Rejected",
    retirado: "I withdrew",
  },
};

export type Locale = keyof typeof dict;
export type Dict = (typeof dict)["es"];

export const STATUSES = [
  "aplicado",
  "cribado",
  "entrevista_1",
  "entrevista_2",
  "entrevista_3",
  "oferta",
  "contratado",
  "rechazado",
  "retirado",
] as const;

export const WORK_MODES = ["presencial", "hibrido", "remoto", "no_especifica"] as const;

export const SOURCES = ["LinkedIn", "InfoJobs", "Indeed", "Web empresa", "Contacto", "Otra"];
