// Un unico diccionario. Sin libreria de i18n: son dos idiomas y textos planos.
export const dict = {
  es: {
    tagline: "Tus candidaturas, ordenadas",
    email: "Correo",
    password: "Contraseña",
    signIn: "Entrar",
    signUp: "Crear cuenta",
    signOut: "Cerrar sesión",
    menu: "Menú",
    language: "Idioma",
    darkMode: "Modo oscuro",
    lightMode: "Modo claro",
    emailExists: "Ya existe una cuenta con ese correo.",
    recoverPassword: "Recuperar contraseña",
    suggestions: "Sugerencias",
    suggestTitle: "¿Qué nos quieres contar?",
    kindError: "Algo falla",
    kindIdea: "Una idea",
    kindDuda: "Una duda",
    suggestPlaceholder: "Cuéntanos qué ha pasado o qué te gustaría. Cuanto más concreto, mejor.",
    suggestSend: "Enviar",
    suggestThanks: "¡Gracias! Lo leeremos y, si hace falta, te contestaremos por correo.",
    suggestFailed: "No se pudo enviar. Inténtalo de nuevo en un momento.",
    checkEmail: "Revisa tu correo para confirmar la cuenta.",
    openInbox: (name: string): string => `Abrir ${name}`,
    forgotPassword: "¿Olvidaste tu contraseña?",
    resetIntro: "Escribe tu correo y te mandamos un enlace para elegir una nueva.",
    sendResetLink: "Enviar enlace",
    resetSent: "Si hay una cuenta con ese correo, te llegará un enlace en unos minutos. Revísalo desde este mismo navegador.",
    backToSignIn: "Volver a entrar",
    linkError: "El enlace ha caducado o ya se usó. Pide uno nuevo.",
    newPassword: "Elige tu nueva contraseña",
    savePassword: "Guardar contraseña",
    ruleLength: "8 caracteres o más",
    ruleLower: "una minúscula",
    ruleUpper: "una mayúscula",
    ruleDigit: "un número",
    ruleSymbol: "un símbolo, como ! ? / . @ #",
    repeatPassword: "Repite la contraseña",
    ruleMatch: "Las dos coinciden",
    showPassword: "Mostrar",
    hidePassword: "Ocultar",
    authError: (code: string) =>
      ({
        over_email_send_rate_limit:
          "Hemos enviado demasiados correos en poco tiempo. Espera una hora y vuelve a intentarlo.",
        over_request_rate_limit: "Demasiados intentos seguidos. Espera unos minutos.",
        weak_password:
          "La contraseña no cumple los requisitos: 8 caracteres o más, con mayúscula, minúscula, número y símbolo.",
        user_already_exists: "Ya existe una cuenta con ese correo. Prueba a entrar o a recuperar la contraseña.",
        email_exists: "Ya existe una cuenta con ese correo. Prueba a entrar o a recuperar la contraseña.",
        invalid_credentials: "Correo o contraseña incorrectos.",
        email_not_confirmed:
          "Todavía no has confirmado tu correo. Busca el email de confirmación (mira también en spam).",
        same_password: "La contraseña nueva tiene que ser distinta de la anterior.",
        signup_disabled: "Ahora mismo no se pueden crear cuentas nuevas.",
      })[code] ?? "Algo ha fallado. Inténtalo de nuevo en unos minutos.",
    newApplication: "Nueva candidatura",
    yourApplications: "Tus candidaturas",
    search: "Buscar por empresa o puesto",
    noResults: (q: string) => `Ninguna candidatura coincide con “${q}”.`,
    cvAttach: "Adjuntar CV (opcional)",
    cvSent: "CV enviado",
    cvUploadNew: "+ Subir otro",
    cvTypePlaceholder: "Tipo de CV, p. ej. CV Data",
    cvHint: "Solo PDF, hasta 5 MB. Si el tipo ya existe, se sustituye por este.",
    cvNotPdf: "Ese archivo no es un PDF.",
    cvTooBig: "El PDF pasa de 5 MB.",
    cvSaveWarning: (msg: string) => `Candidatura guardada, pero el CV no se pudo subir: ${msg}`,
    myCvs: "Mis CVs",
    importCsv: "Importar",
    importCta: "Subir mi tabla",
    importTitle: "¿Ya las tienes apuntadas en algún sitio?",
    importIntro:
      "Si llevas la cuenta en un Excel, en Sheets o en una tabla, tráela y rellenamos tus candidaturas por ti.",
    importDrop: "Arrastra aquí tu archivo, o",
    importChoose: "elige uno",
    importHint: "CSV o TSV. Lo único imprescindible son dos columnas: empresa y puesto.",
    importPaste: "…o pega aquí las celdas copiadas de tu hoja",
    importXlsx:
      "Los archivos de Excel (.xlsx) no se pueden leer tal cual. En Excel: Archivo → Guardar como → CSV. En Sheets: Archivo → Descargar → CSV. O copia las celdas y pégalas abajo.",
    importTooBig: "El archivo es demasiado grande. El máximo son 2 MB.",
    importLink:
      "Eso es un enlace, no un archivo: arrastrando desde Drive el navegador no manda la hoja. Descárgala como CSV (Archivo → Descargar → CSV) o copia las celdas y pégalas abajo.",
    importNothing:
      "No hemos encontrado ninguna candidatura. Hacen falta dos columnas: una con la empresa y otra con el puesto.",
    importFound: (n: number): string =>
      n === 1 ? "Hemos entendido 1 candidatura:" : `Hemos entendido ${n} candidaturas:`,
    importMore: (n: number): string => (n === 1 ? "y 1 más" : `y ${n} más`),
    importIgnored: (cols: string): string => `Columnas que no usamos: ${cols}`,
    importTooMany: (n: number): string => `Se importarán las primeras ${n}. El resto, en otra tanda.`,
    importDo: (n: number): string =>
      n === 1 ? "Importar 1 candidatura" : `Importar ${n} candidaturas`,
    importDone: (n: number): string =>
      n === 1 ? "Listo. 1 candidatura añadida." : `Listo. ${n} candidaturas añadidas.`,
    importFailed: "No se han podido importar. Vuelve a intentarlo.",
    importSkipped: (n: number): string =>
      n === 1 ? "1 ya la tenías y se salta." : `${n} ya las tenías y se saltan.`,
    duplicate: "Ya tienes esa candidatura: misma empresa, mismo puesto y misma fecha.",
    exportCsv: "Exportar CSV",
    csvSalaryMin: "Salario mínimo",
    csvSalaryMax: "Salario máximo",
    csvContacted: "Contactado",
    help: "Ayuda",
    refresh: "Actualizar",
    install: "Instalar en el móvil",
    deleteAccount: "Borrar mi cuenta",
    deleteAccountWarning: "Se borrarán tu cuenta, tus candidaturas y tus CVs. No se puede deshacer.",
    deleteAccountConfirm: "Sí, borrar todo",
    installIos1: "Toca el botón de compartir",
    installIos2: "Baja en la lista que se abre",
    installIos3: "Elige «Añadir a pantalla de inicio»",
    cvView: "Ver",
    cvDownload: "Descargar",
    cvReplace: "Cambiar",
    cvReplaced: "CV cambiado. Las candidaturas que lo usaban ya apuntan al nuevo.",
    cvReplaceFailed: "No se pudo cambiar el CV. Inténtalo de nuevo en un momento.",
    cvDeleted: "CV borrado",
    cvDeleteFailed: "No se ha podido borrar. Vuelve a intentarlo.",
    cvInUse: (n: number): string =>
      n === 0
        ? "No lo usa ninguna candidatura."
        : n === 1
          ? "Lo usa 1 candidatura, que se quedará sin CV."
          : `Lo usan ${n} candidaturas, que se quedarán sin CV.`,
    cvNone: "Todavía no has subido ningún CV. Se suben al crear o editar una candidatura.",
    edit: "Editar",
    delete: "Borrar",
    confirmDelete: "¿Seguro? Pulsa otra vez",
    summaryActive: "En marcha",
    summaryWaiting: "Sin respuesta",
    summaryInterviews: "En entrevistas",
    summaryDue: "Toca contactar",
    clearFilter: "Quitar filtro",
    select: "Seleccionar",
    selectAll: "Todas",
    selected: (n: number): string =>
      n === 0 ? "Ninguna seleccionada" : n === 1 ? "1 seleccionada" : `${n} seleccionadas`,
    filters: "Filtros",
    lastDays: (n: number): string => (n === 7 ? "Última semana" : n === 30 ? "Último mes" : "Últimos 3 meses"),
    noMatches: "Ninguna candidatura cumple estos filtros.",
    pickOne: "Toca una candidatura y verás aquí sus detalles.",
    shown: (n: number, total: number) => `${n} de ${total} candidaturas`,
    viewList: "Lista",
    viewCompanies: "Empresas",
    viewRoles: "Puestos",
    viewRejected: "Rechazadas",
    salaryShort: "Salario",
    offer: "Oferta",
    viewOffer: "Ver oferta",
    note: "Nota",
    addNote: "+ Añadir nota",
    notePlaceholder: "Red flags, nombre del recruiter, qué te preguntaron…",
    company: "Empresa",
    role: "Puesto",
    source: "Vía",
    sourceHint: "Dónde viste la oferta o por dónde aplicaste.",
    url: "Enlace a la oferta",
    workMode: "Modalidad",
    workModeHint: "La que ofrece la empresa en la oferta.",
    salary: "Salario (€)",
    salaryHint: "25 = 25.000 €. Si es mensual, como en prácticas, pon el importe tal cual: 300.",
    min: "mínimo",
    max: "máximo",
    notSpecified: "No especifica",
    appliedOn: "Fecha",
    status: "Estado",
    statusHint: "En qué punto está esta candidatura ahora mismo.",
    cv: "CV enviado",
    followUpOn: "Seguimiento",
    followUpHint: "Te lo proponemos a 15 días. Cámbialo si quieres.",
    save: "Guardar",
    cancel: "Cancelar",
    empty: "Todavía no has registrado ninguna candidatura.",
    daysAgo: (n: number) => (n === 0 ? "hoy" : n === 1 ? "hace 1 día" : `hace ${n} días`),
    total: "candidaturas",
    totalOne: "candidatura",
    notContacted: "¿Ya contactaste?",
    yes: "Sí",
    notYet: "Aún no",
    followUpToday: "Toca contactar hoy",
    followUpDue: (n: number) => (n === 1 ? "Deberías haber contactado hace 1 día" : `Deberías haber contactado hace ${n} días`),
    followUpSoon: (n: number) => (n === 1 ? "Contactar mañana" : `Contactar en ${n} días`),
    remindLater: "Recordar 7 días más",
    noFollowUp: "No hace falta contactar",
    followUpOff: "Sin recordatorio",
    followUpBack: "Activar",
    optional: "opcional",
    presencial: "Presencial",
    hibrido: "Híbrido",
    remoto: "Remoto",
    no_especifica: "No especifica",
    aplicado: "Sin respuesta",
    cribado: "Me contactaron",
    entrevista_1: "1ª entrevista",
    entrevista_2: "2ª entrevista",
    entrevista_3: "3ª entrevista",
    oferta: "Oferta recibida",
    contratado: "¡Contratado!",
    rechazado: "Rechazado",
    retirado: "Me retiré",
  },
  en: {
    tagline: "Your job applications, sorted",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    signUp: "Sign up",
    signOut: "Sign out",
    menu: "Menu",
    language: "Language",
    darkMode: "Dark mode",
    lightMode: "Light mode",
    emailExists: "There's already an account with that email.",
    recoverPassword: "Reset password",
    suggestions: "Feedback",
    suggestTitle: "What would you like to tell us?",
    kindError: "Something's broken",
    kindIdea: "An idea",
    kindDuda: "A question",
    suggestPlaceholder: "Tell us what happened or what you'd like. The more specific, the better.",
    suggestSend: "Send",
    suggestThanks: "Thanks! We'll read it and, if needed, reply by email.",
    suggestFailed: "It couldn't be sent. Try again in a moment.",
    checkEmail: "Check your email to confirm your account.",
    openInbox: (name: string): string => `Open ${name}`,
    forgotPassword: "Forgot your password?",
    resetIntro: "Enter your email and we'll send you a link to choose a new one.",
    sendResetLink: "Send link",
    resetSent: "If there's an account with that email, a link is on its way. Open it in this same browser.",
    backToSignIn: "Back to sign in",
    linkError: "That link has expired or was already used. Request a new one.",
    newPassword: "Choose your new password",
    savePassword: "Save password",
    ruleLength: "8 or more characters",
    ruleLower: "a lowercase letter",
    ruleUpper: "an uppercase letter",
    ruleDigit: "a number",
    ruleSymbol: "a symbol, like ! ? / . @ #",
    repeatPassword: "Repeat your password",
    ruleMatch: "Both match",
    showPassword: "Show",
    hidePassword: "Hide",
    authError: (code: string) =>
      ({
        over_email_send_rate_limit: "We've sent too many emails in a short time. Wait an hour and try again.",
        over_request_rate_limit: "Too many attempts in a row. Wait a few minutes.",
        weak_password:
          "The password doesn't meet the requirements: 8+ characters, with uppercase, lowercase, number and symbol.",
        user_already_exists: "There's already an account with that email. Try signing in or resetting your password.",
        email_exists: "There's already an account with that email. Try signing in or resetting your password.",
        invalid_credentials: "Wrong email or password.",
        email_not_confirmed: "You haven't confirmed your email yet. Look for the confirmation email (check spam too).",
        same_password: "The new password must be different from the old one.",
        signup_disabled: "New accounts can't be created right now.",
      })[code] ?? "Something went wrong. Try again in a few minutes.",
    newApplication: "New application",
    yourApplications: "Your applications",
    search: "Search by company or role",
    noResults: (q: string) => `No application matches “${q}”.`,
    cvAttach: "Attach CV (optional)",
    cvSent: "CV sent",
    cvUploadNew: "+ Upload another",
    cvTypePlaceholder: "CV type, e.g. Data CV",
    cvHint: "PDF only, up to 5 MB. If the type already exists, it gets replaced.",
    cvNotPdf: "That file is not a PDF.",
    cvTooBig: "The PDF is larger than 5 MB.",
    cvSaveWarning: (msg: string) => `Application saved, but the CV couldn't be uploaded: ${msg}`,
    myCvs: "My CVs",
    importCsv: "Import",
    importCta: "Upload my sheet",
    importTitle: "Already tracking them somewhere?",
    importIntro:
      "If you keep them in Excel, in Sheets or in any table, bring it over and we'll fill in your applications for you.",
    importDrop: "Drop your file here, or",
    importChoose: "choose one",
    importHint: "CSV or TSV. All you really need are two columns: company and role.",
    importPaste: "…or paste the cells copied from your sheet here",
    importXlsx:
      "Excel files (.xlsx) can't be read as they are. In Excel: File → Save as → CSV. In Sheets: File → Download → CSV. Or copy the cells and paste them below.",
    importTooBig: "That file is too big. The limit is 2 MB.",
    importLink:
      "That's a link, not a file: dragging from Drive, the browser doesn't send the sheet itself. Download it as CSV (File → Download → CSV) or copy the cells and paste them below.",
    importNothing:
      "We found no applications in there. You need two columns: one with the company and one with the role.",
    importFound: (n: number): string =>
      n === 1 ? "We understood 1 application:" : `We understood ${n} applications:`,
    importMore: (n: number): string => (n === 1 ? "and 1 more" : `and ${n} more`),
    importIgnored: (cols: string): string => `Columns we don't use: ${cols}`,
    importTooMany: (n: number): string => `The first ${n} will be imported. The rest, in another batch.`,
    importDo: (n: number): string => (n === 1 ? "Import 1 application" : `Import ${n} applications`),
    importDone: (n: number): string =>
      n === 1 ? "Done. 1 application added." : `Done. ${n} applications added.`,
    importFailed: "We couldn't import them. Try again.",
    importSkipped: (n: number): string =>
      n === 1 ? "1 you already had, skipped." : `${n} you already had, skipped.`,
    duplicate: "You already have that one: same company, same role and same date.",
    exportCsv: "Export CSV",
    csvSalaryMin: "Minimum salary",
    csvSalaryMax: "Maximum salary",
    csvContacted: "Followed up",
    help: "Help",
    refresh: "Refresh",
    install: "Install on your phone",
    deleteAccount: "Delete my account",
    deleteAccountWarning: "Your account, your applications and your CVs will be deleted. This can't be undone.",
    deleteAccountConfirm: "Yes, delete everything",
    installIos1: "Tap the share button",
    installIos2: "Scroll down the list that opens",
    installIos3: "Pick “Add to Home Screen”",
    cvView: "View",
    cvDownload: "Download",
    cvReplace: "Replace",
    cvReplaced: "CV replaced. The applications using it now point to the new one.",
    cvReplaceFailed: "The CV couldn't be replaced. Try again in a moment.",
    cvDeleted: "CV deleted",
    cvDeleteFailed: "Couldn't delete it. Try again.",
    cvInUse: (n: number): string =>
      n === 0
        ? "No application uses it."
        : n === 1
          ? "1 application uses it, and will be left without a CV."
          : `${n} applications use it, and will be left without a CV.`,
    cvNone: "You haven't uploaded any CV yet. You upload them when creating or editing an application.",
    edit: "Edit",
    delete: "Delete",
    confirmDelete: "Sure? Tap again",
    summaryActive: "Active",
    summaryWaiting: "No reply",
    summaryInterviews: "Interviewing",
    summaryDue: "Follow up due",
    clearFilter: "Clear filter",
    select: "Select",
    selectAll: "All",
    selected: (n: number): string =>
      n === 0 ? "None selected" : n === 1 ? "1 selected" : `${n} selected`,
    filters: "Filters",
    lastDays: (n: number): string => (n === 7 ? "Last week" : n === 30 ? "Last month" : "Last 3 months"),
    noMatches: "No applications match these filters.",
    pickOne: "Tap an application and its details show up here.",
    shown: (n: number, total: number) => `${n} of ${total} applications`,
    viewList: "List",
    viewCompanies: "Companies",
    viewRoles: "Roles",
    viewRejected: "Rejected",
    salaryShort: "Salary",
    offer: "Posting",
    viewOffer: "View posting",
    note: "Note",
    addNote: "+ Add note",
    notePlaceholder: "Red flags, the recruiter's name, what they asked you…",
    company: "Company",
    role: "Role",
    source: "Source",
    sourceHint: "Where you saw it or how you applied.",
    url: "Job posting link",
    workMode: "Work mode",
    workModeHint: "What the company offers in the posting.",
    salary: "Salary (€)",
    salaryHint: "25 = €25,000. If it's monthly, like an internship, type the exact amount: 300.",
    min: "min",
    max: "max",
    notSpecified: "Not specified",
    appliedOn: "Date",
    status: "Status",
    statusHint: "Where this application stands right now.",
    cv: "CV sent",
    followUpOn: "Follow-up",
    followUpHint: "Suggested 15 days ahead. Change it if you want.",
    save: "Save",
    cancel: "Cancel",
    empty: "You haven't logged any application yet.",
    daysAgo: (n: number) => (n === 0 ? "today" : n === 1 ? "1 day ago" : `${n} days ago`),
    total: "applications",
    totalOne: "application",
    notContacted: "Followed up yet?",
    yes: "Yes",
    notYet: "Not yet",
    followUpToday: "Time to follow up today",
    followUpDue: (n: number) => (n === 1 ? "You should have followed up 1 day ago" : `You should have followed up ${n} days ago`),
    followUpSoon: (n: number) => (n === 1 ? "Follow up tomorrow" : `Follow up in ${n} days`),
    remindLater: "Remind me 7 days later",
    noFollowUp: "No need to follow up",
    followUpOff: "Reminder off",
    followUpBack: "Turn on",
    optional: "optional",
    presencial: "On-site",
    hibrido: "Hybrid",
    remoto: "Remote",
    no_especifica: "Not specified",
    aplicado: "No reply yet",
    cribado: "They reached out",
    entrevista_1: "1st interview",
    entrevista_2: "2nd interview",
    entrevista_3: "3rd interview",
    oferta: "Offer received",
    contratado: "Hired!",
    rechazado: "Rejected",
    retirado: "I withdrew",
  },
};

export type Locale = keyof typeof dict;
export type Dict = (typeof dict)["es"];

export const STATUSES = [
  "aplicado",
  "cribado",
  "entrevista_1",
  "entrevista_2",
  "entrevista_3",
  "oferta",
  "contratado",
  "rechazado",
  "retirado",
] as const;

export const WORK_MODES = ["presencial", "hibrido", "remoto", "no_especifica"] as const;

export const SOURCES = ["LinkedIn", "InfoJobs", "Indeed", "Glassdoor", "Web empresa", "Contacto", "Otra"];
